### ISSUE TITLE
build on python 3.10 ubuntu 22 fails

### ISSUE THREAD

**Issue by acostaja** [1200wd/bitcoinlib#227]
getting this error:

> In file included from src/curveMath.c:1:
>       src/curveMath.h:4:10: fatal error: Python.h: No existe el archivo o el directorio
>           4 | #include <Python.h>
>             |          ^~~~~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
>       [end of output]

installing by PIP3 / Ubuntu 22.04 beta

consider also ubuntu's 22 Openssl3 deprecates (and renders cumbersome its legacy access) RIPEMD160, the issue is set to propagate

**Comment by acostaja** [comment]
>

**Comment by acostaja** [comment]
> Are you sure the Python development package is installed?
> 
> `apt install python3.10-dev`
> 
> All unittests seem to work here in python 3.10.
That's is, installed correctly now

**Comment by FKrauss** [comment]
just adding something here. I faced the same issue installing bitcoinlib on Ubuntu 22 (not Beta anymore).

The solution above didn't work but following the instructions [here](https://github.com/deepgully/pyzil/issues/6) did. Which consists in running the following:
* `sudo apt-get install libgmp-dev`  << installs this library
* `sudo pip3 install bitcoinlib` << then it works fine
